package com.conveyal.trafficprobe;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: location.proto



public final class TrafficProbeProtos {
  private TrafficProbeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LocationUpdateOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required int64 time = 1;
    boolean hasTime();
    long getTime();
    
    // required int64 phone = 2;
    boolean hasPhone();
    long getPhone();
    
    // repeated .trafficprobe.LocationUpdate.Location location = 3;
    java.util.List<com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location> 
        getLocationList();
    com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location getLocation(int index);
    int getLocationCount();
    
    // optional float battery = 4;
    boolean hasBattery();
    float getBattery();
    
    // optional int32 network = 5;
    boolean hasNetwork();
    int getNetwork();
    
    // optional bool charging = 6;
    boolean hasCharging();
    boolean getCharging();
    
    // optional float level = 7;
    boolean hasLevel();
    float getLevel();
    
    // optional string gps = 8;
    boolean hasGps();
    String getGps();
  }
  public static final class LocationUpdate extends
      com.google.protobuf.GeneratedMessageLite
      implements LocationUpdateOrBuilder {
    // Use LocationUpdate.newBuilder() to construct.
    private LocationUpdate(Builder builder) {
      super(builder);
    }
    private LocationUpdate(boolean noInit) {}
    
    private static final LocationUpdate defaultInstance;
    public static LocationUpdate getDefaultInstance() {
      return defaultInstance;
    }
    
    public LocationUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public interface LocationOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {
      
      // required float lat = 5;
      boolean hasLat();
      float getLat();
      
      // required float lon = 6;
      boolean hasLon();
      float getLon();
      
      // optional int32 timeoffset = 1;
      boolean hasTimeoffset();
      int getTimeoffset();
      
      // optional int32 velocity = 2;
      boolean hasVelocity();
      int getVelocity();
      
      // optional int32 accuracy = 3;
      boolean hasAccuracy();
      int getAccuracy();
      
      // optional int32 heading = 4;
      boolean hasHeading();
      int getHeading();
    }
    public static final class Location extends
        com.google.protobuf.GeneratedMessageLite
        implements LocationOrBuilder {
      // Use Location.newBuilder() to construct.
      private Location(Builder builder) {
        super(builder);
      }
      private Location(boolean noInit) {}
      
      private static final Location defaultInstance;
      public static Location getDefaultInstance() {
        return defaultInstance;
      }
      
      public Location getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      private int bitField0_;
      // required float lat = 5;
      public static final int LAT_FIELD_NUMBER = 5;
      private float lat_;
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public float getLat() {
        return lat_;
      }
      
      // required float lon = 6;
      public static final int LON_FIELD_NUMBER = 6;
      private float lon_;
      public boolean hasLon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getLon() {
        return lon_;
      }
      
      // optional int32 timeoffset = 1;
      public static final int TIMEOFFSET_FIELD_NUMBER = 1;
      private int timeoffset_;
      public boolean hasTimeoffset() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getTimeoffset() {
        return timeoffset_;
      }
      
      // optional int32 velocity = 2;
      public static final int VELOCITY_FIELD_NUMBER = 2;
      private int velocity_;
      public boolean hasVelocity() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getVelocity() {
        return velocity_;
      }
      
      // optional int32 accuracy = 3;
      public static final int ACCURACY_FIELD_NUMBER = 3;
      private int accuracy_;
      public boolean hasAccuracy() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getAccuracy() {
        return accuracy_;
      }
      
      // optional int32 heading = 4;
      public static final int HEADING_FIELD_NUMBER = 4;
      private int heading_;
      public boolean hasHeading() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getHeading() {
        return heading_;
      }
      
      private void initFields() {
        lat_ = 0F;
        lon_ = 0F;
        timeoffset_ = 0;
        velocity_ = 0;
        accuracy_ = 0;
        heading_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasLat()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLon()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(1, timeoffset_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(2, velocity_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeInt32(3, accuracy_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeInt32(4, heading_);
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeFloat(5, lat_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(6, lon_);
        }
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, timeoffset_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, velocity_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, accuracy_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, heading_);
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(5, lat_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(6, lon_);
        }
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location, Builder>
          implements com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.LocationOrBuilder {
        // Construct using com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          lat_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000001);
          lon_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          timeoffset_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          velocity_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          accuracy_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          heading_ = 0;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location getDefaultInstanceForType() {
          return com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location.getDefaultInstance();
        }
        
        public com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location build() {
          com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location buildPartial() {
          com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location result = new com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.lat_ = lat_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.lon_ = lon_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.timeoffset_ = timeoffset_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.velocity_ = velocity_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.accuracy_ = accuracy_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.heading_ = heading_;
          result.bitField0_ = to_bitField0_;
          return result;
        }
        
        public Builder mergeFrom(com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location other) {
          if (other == com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location.getDefaultInstance()) return this;
          if (other.hasLat()) {
            setLat(other.getLat());
          }
          if (other.hasLon()) {
            setLon(other.getLon());
          }
          if (other.hasTimeoffset()) {
            setTimeoffset(other.getTimeoffset());
          }
          if (other.hasVelocity()) {
            setVelocity(other.getVelocity());
          }
          if (other.hasAccuracy()) {
            setAccuracy(other.getAccuracy());
          }
          if (other.hasHeading()) {
            setHeading(other.getHeading());
          }
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasLat()) {
            
            return false;
          }
          if (!hasLon()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                
                return this;
              default: {
                if (!parseUnknownField(input, extensionRegistry, tag)) {
                  
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000004;
                timeoffset_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000008;
                velocity_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000010;
                accuracy_ = input.readInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000020;
                heading_ = input.readInt32();
                break;
              }
              case 45: {
                bitField0_ |= 0x00000001;
                lat_ = input.readFloat();
                break;
              }
              case 53: {
                bitField0_ |= 0x00000002;
                lon_ = input.readFloat();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required float lat = 5;
        private float lat_ ;
        public boolean hasLat() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public float getLat() {
          return lat_;
        }
        public Builder setLat(float value) {
          bitField0_ |= 0x00000001;
          lat_ = value;
          
          return this;
        }
        public Builder clearLat() {
          bitField0_ = (bitField0_ & ~0x00000001);
          lat_ = 0F;
          
          return this;
        }
        
        // required float lon = 6;
        private float lon_ ;
        public boolean hasLon() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public float getLon() {
          return lon_;
        }
        public Builder setLon(float value) {
          bitField0_ |= 0x00000002;
          lon_ = value;
          
          return this;
        }
        public Builder clearLon() {
          bitField0_ = (bitField0_ & ~0x00000002);
          lon_ = 0F;
          
          return this;
        }
        
        // optional int32 timeoffset = 1;
        private int timeoffset_ ;
        public boolean hasTimeoffset() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public int getTimeoffset() {
          return timeoffset_;
        }
        public Builder setTimeoffset(int value) {
          bitField0_ |= 0x00000004;
          timeoffset_ = value;
          
          return this;
        }
        public Builder clearTimeoffset() {
          bitField0_ = (bitField0_ & ~0x00000004);
          timeoffset_ = 0;
          
          return this;
        }
        
        // optional int32 velocity = 2;
        private int velocity_ ;
        public boolean hasVelocity() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        public int getVelocity() {
          return velocity_;
        }
        public Builder setVelocity(int value) {
          bitField0_ |= 0x00000008;
          velocity_ = value;
          
          return this;
        }
        public Builder clearVelocity() {
          bitField0_ = (bitField0_ & ~0x00000008);
          velocity_ = 0;
          
          return this;
        }
        
        // optional int32 accuracy = 3;
        private int accuracy_ ;
        public boolean hasAccuracy() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        public int getAccuracy() {
          return accuracy_;
        }
        public Builder setAccuracy(int value) {
          bitField0_ |= 0x00000010;
          accuracy_ = value;
          
          return this;
        }
        public Builder clearAccuracy() {
          bitField0_ = (bitField0_ & ~0x00000010);
          accuracy_ = 0;
          
          return this;
        }
        
        // optional int32 heading = 4;
        private int heading_ ;
        public boolean hasHeading() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        public int getHeading() {
          return heading_;
        }
        public Builder setHeading(int value) {
          bitField0_ |= 0x00000020;
          heading_ = value;
          
          return this;
        }
        public Builder clearHeading() {
          bitField0_ = (bitField0_ & ~0x00000020);
          heading_ = 0;
          
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:trafficprobe.LocationUpdate.Location)
      }
      
      static {
        defaultInstance = new Location(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:trafficprobe.LocationUpdate.Location)
    }
    
    private int bitField0_;
    // required int64 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTime() {
      return time_;
    }
    
    // required int64 phone = 2;
    public static final int PHONE_FIELD_NUMBER = 2;
    private long phone_;
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getPhone() {
      return phone_;
    }
    
    // repeated .trafficprobe.LocationUpdate.Location location = 3;
    public static final int LOCATION_FIELD_NUMBER = 3;
    private java.util.List<com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location> location_;
    public java.util.List<com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location> getLocationList() {
      return location_;
    }
    public java.util.List<? extends com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.LocationOrBuilder> 
        getLocationOrBuilderList() {
      return location_;
    }
    public int getLocationCount() {
      return location_.size();
    }
    public com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location getLocation(int index) {
      return location_.get(index);
    }
    public com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.LocationOrBuilder getLocationOrBuilder(
        int index) {
      return location_.get(index);
    }
    
    // optional float battery = 4;
    public static final int BATTERY_FIELD_NUMBER = 4;
    private float battery_;
    public boolean hasBattery() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getBattery() {
      return battery_;
    }
    
    // optional int32 network = 5;
    public static final int NETWORK_FIELD_NUMBER = 5;
    private int network_;
    public boolean hasNetwork() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getNetwork() {
      return network_;
    }
    
    // optional bool charging = 6;
    public static final int CHARGING_FIELD_NUMBER = 6;
    private boolean charging_;
    public boolean hasCharging() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getCharging() {
      return charging_;
    }
    
    // optional float level = 7;
    public static final int LEVEL_FIELD_NUMBER = 7;
    private float level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public float getLevel() {
      return level_;
    }
    
    // optional string gps = 8;
    public static final int GPS_FIELD_NUMBER = 8;
    private java.lang.Object gps_;
    public boolean hasGps() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getGps() {
      java.lang.Object ref = gps_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          gps_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGpsBytes() {
      java.lang.Object ref = gps_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        gps_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      time_ = 0L;
      phone_ = 0L;
      location_ = java.util.Collections.emptyList();
      battery_ = 0F;
      network_ = 0;
      charging_ = false;
      level_ = 0F;
      gps_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getLocationCount(); i++) {
        if (!getLocation(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, phone_);
      }
      for (int i = 0; i < location_.size(); i++) {
        output.writeMessage(3, location_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(4, battery_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, network_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(6, charging_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(7, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getGpsBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, phone_);
      }
      for (int i = 0; i < location_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, location_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, battery_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, network_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, charging_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getGpsBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate, Builder>
        implements com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdateOrBuilder {
      // Construct using com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        phone_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        location_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        battery_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        network_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        charging_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        level_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        gps_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate getDefaultInstanceForType() {
        return com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.getDefaultInstance();
      }
      
      public com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate build() {
        com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate buildPartial() {
        com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate result = new com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.phone_ = phone_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          location_ = java.util.Collections.unmodifiableList(location_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.location_ = location_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.battery_ = battery_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.network_ = network_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.charging_ = charging_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.gps_ = gps_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate other) {
        if (other == com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (!other.location_.isEmpty()) {
          if (location_.isEmpty()) {
            location_ = other.location_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureLocationIsMutable();
            location_.addAll(other.location_);
          }
          
        }
        if (other.hasBattery()) {
          setBattery(other.getBattery());
        }
        if (other.hasNetwork()) {
          setNetwork(other.getNetwork());
        }
        if (other.hasCharging()) {
          setCharging(other.getCharging());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasGps()) {
          setGps(other.getGps());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        if (!hasPhone()) {
          
          return false;
        }
        for (int i = 0; i < getLocationCount(); i++) {
          if (!getLocation(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              phone_ = input.readInt64();
              break;
            }
            case 26: {
              com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location.Builder subBuilder = com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLocation(subBuilder.buildPartial());
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              battery_ = input.readFloat();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              network_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              charging_ = input.readBool();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              level_ = input.readFloat();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              gps_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 time = 1;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        
        return this;
      }
      
      // required int64 phone = 2;
      private long phone_ ;
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getPhone() {
        return phone_;
      }
      public Builder setPhone(long value) {
        bitField0_ |= 0x00000002;
        phone_ = value;
        
        return this;
      }
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000002);
        phone_ = 0L;
        
        return this;
      }
      
      // repeated .trafficprobe.LocationUpdate.Location location = 3;
      private java.util.List<com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location> location_ =
        java.util.Collections.emptyList();
      private void ensureLocationIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          location_ = new java.util.ArrayList<com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location>(location_);
          bitField0_ |= 0x00000004;
         }
      }
      
      public java.util.List<com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location> getLocationList() {
        return java.util.Collections.unmodifiableList(location_);
      }
      public int getLocationCount() {
        return location_.size();
      }
      public com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location getLocation(int index) {
        return location_.get(index);
      }
      public Builder setLocation(
          int index, com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationIsMutable();
        location_.set(index, value);
        
        return this;
      }
      public Builder setLocation(
          int index, com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location.Builder builderForValue) {
        ensureLocationIsMutable();
        location_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addLocation(com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationIsMutable();
        location_.add(value);
        
        return this;
      }
      public Builder addLocation(
          int index, com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationIsMutable();
        location_.add(index, value);
        
        return this;
      }
      public Builder addLocation(
          com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location.Builder builderForValue) {
        ensureLocationIsMutable();
        location_.add(builderForValue.build());
        
        return this;
      }
      public Builder addLocation(
          int index, com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location.Builder builderForValue) {
        ensureLocationIsMutable();
        location_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllLocation(
          java.lang.Iterable<? extends com.conveyal.trafficprobe.TrafficProbeProtos.LocationUpdate.Location> values) {
        ensureLocationIsMutable();
        super.addAll(values, location_);
        
        return this;
      }
      public Builder clearLocation() {
        location_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }
      public Builder removeLocation(int index) {
        ensureLocationIsMutable();
        location_.remove(index);
        
        return this;
      }
      
      // optional float battery = 4;
      private float battery_ ;
      public boolean hasBattery() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getBattery() {
        return battery_;
      }
      public Builder setBattery(float value) {
        bitField0_ |= 0x00000008;
        battery_ = value;
        
        return this;
      }
      public Builder clearBattery() {
        bitField0_ = (bitField0_ & ~0x00000008);
        battery_ = 0F;
        
        return this;
      }
      
      // optional int32 network = 5;
      private int network_ ;
      public boolean hasNetwork() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getNetwork() {
        return network_;
      }
      public Builder setNetwork(int value) {
        bitField0_ |= 0x00000010;
        network_ = value;
        
        return this;
      }
      public Builder clearNetwork() {
        bitField0_ = (bitField0_ & ~0x00000010);
        network_ = 0;
        
        return this;
      }
      
      // optional bool charging = 6;
      private boolean charging_ ;
      public boolean hasCharging() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getCharging() {
        return charging_;
      }
      public Builder setCharging(boolean value) {
        bitField0_ |= 0x00000020;
        charging_ = value;
        
        return this;
      }
      public Builder clearCharging() {
        bitField0_ = (bitField0_ & ~0x00000020);
        charging_ = false;
        
        return this;
      }
      
      // optional float level = 7;
      private float level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public float getLevel() {
        return level_;
      }
      public Builder setLevel(float value) {
        bitField0_ |= 0x00000040;
        level_ = value;
        
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000040);
        level_ = 0F;
        
        return this;
      }
      
      // optional string gps = 8;
      private java.lang.Object gps_ = "";
      public boolean hasGps() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getGps() {
        java.lang.Object ref = gps_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          gps_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGps(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        gps_ = value;
        
        return this;
      }
      public Builder clearGps() {
        bitField0_ = (bitField0_ & ~0x00000080);
        gps_ = getDefaultInstance().getGps();
        
        return this;
      }
      void setGps(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        gps_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:trafficprobe.LocationUpdate)
    }
    
    static {
      defaultInstance = new LocationUpdate(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:trafficprobe.LocationUpdate)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
